### ISSUE TITLE
Crashing on latest update

### ISSUE THREAD

**Issue by rodrigoswz** [Florianisme/WakeOnLan#14]
When opening the app it crashes immediately. It happens on both my phone and tablet.

Devices:
- POCO F3
- Xiaomi Pad 5

ROM:
ArrowOS 13.1 - Android 13 (TQ2A.230505.002)

App:
1.8.2

```
FATAL EXCEPTION: main
Process: de.florianisme.wakeonlan, PID: 4396
java.lang.RuntimeException: Unable to start activity ComponentInfo{de.florianisme.wakeonlan/de.florianisme.wakeonlan.ui.MainActivity}: android.view.InflateException: Binary XML file line #30 in de.florianisme.wakeonlan:layout/activity_main: Binary XML file line #18 in de.florianisme.wakeonlan:layout/content_main: Error inflating class fragment
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3650)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3787)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2303)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7893)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
Caused by: android.view.InflateException: Binary XML file line #30 in de.florianisme.wakeonlan:layout/activity_main: Binary XML file line #18 in de.florianisme.wakeonlan:layout/content_main: Error inflating class fragment
Caused by: android.view.InflateException: Binary XML file line #18 in de.florianisme.wakeonlan:layout/content_main: Error inflating class fragment
Caused by: java.lang.IllegalStateException: Room cannot verify the data integrity. Looks like you've changed schema but forgot to update the version number. You can simply fix this by increasing the version number. Expected identity hash: 8b5b8c030c84ab5c63e79bc79b182635, found: 16901a583cda1c3abb16953c6aa663be
	at androidx.room.RoomOpenHelper.checkIdentity(RoomOpenHelper.kt:147)
	at androidx.room.RoomOpenHelper.onOpen(RoomOpenHelper.kt:128)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onOpen(FrameworkSQLiteOpenHelper.kt:279)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:427)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:316)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableOrReadableDatabase(FrameworkSQLiteOpenHelper.kt:231)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.innerGetDatabase(FrameworkSQLiteOpenHelper.kt:189)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getSupportDatabase(FrameworkSQLiteOpenHelper.kt:151)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.kt:104)
	at androidx.room.RoomDatabase.inTransaction(RoomDatabase.kt:629)
	at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.kt:448)
	at de.florianisme.wakeonlan.persistence.DeviceDao_Impl.getAll(DeviceDao_Impl.java:252)
	at de.florianisme.wakeonlan.persistence.repository.DeviceRepository.getAll(DeviceRepository.java:33)
	at de.florianisme.wakeonlan.ui.list.DeviceListFragment.instantiateRecyclerView(DeviceListFragment.java:54)
	at de.florianisme.wakeonlan.ui.list.DeviceListFragment.onViewCreated(DeviceListFragment.java:43)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3128)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:552)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1433)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2977)
	at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:2888)
	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3129)
	at androidx.fragment.app.FragmentStateManager.ensureInflatedView(FragmentStateManager.java:394)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:260)
	at androidx.fragment.app.FragmentLayoutInflaterFactory.onCreateView(FragmentLayoutInflaterFactory.java:142)
	at androidx.fragment.app.FragmentController.onCreateView(FragmentController.java:136)
	at androidx.fragment.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:248)
	at androidx.fragment.app.FragmentActivity.onCreateView(FragmentActivity.java:227)
	at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1081)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1009)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:973)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1135)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1096)
	at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1275)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1131)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1096)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1138)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1096)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:686)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:538)
	at de.florianisme.wakeonlan.databinding.ActivityMainBinding.inflate(ActivityMainBinding.java:54)
	at de.florianisme.wakeonlan.databinding.ActivityMainBinding.inflate(ActivityMainBinding.java:48)
	at de.florianisme.wakeonlan.ui.MainActivity.onCreate(MainActivity.java:34)
	at android.app.Activity.performCreate(Activity.java:8341)
	at android.app.Activity.performCreate(Activity.java:8320)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1420)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3631)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3787)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2303)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7893)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
```

**Comment by Florianisme** [comment]
Hey, can you try a reinstall? I think there was a backwards-incompatible change between the last two beta releases.

**Comment by rodrigoswz** [comment]
Yes, clean data works! Sorry, I don't know why I didn't try this before 😅

**Comment by Florianisme** [comment]
Good to know! So looks like you are probably the only one who updated to both beta versions 😅

And I guess Google restored the application data when you reinstalled the app from the Play Store. Thanks for the feedback, but shouldn't happen to any non-beta users.
